server:
  port: 80
user1:
  name: Tom
  age: 190
  favorite: [basketball,football]
basedir: "c:/windows"
temp: ${basedir}/temps
work: ${basedir}/works
datasource:
  url: abc
  port: 3306
  user: root
  password: 123589
  driver: mysqldrivers